### ISSUE TITLE
Warn users about scikit-learn version mismatch at runtime

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-classifier#48]
For trained DBs, it would be really nice to warn users that they are using a version of scikit-learn that is incompatible with the version used to create the DB. We could do this by updating the DirFmt to encode scikit-learn version, then validate version at runtime.

**Comment by BenKaehler** [comment]
Thanks @thermokarst, scikit-learn already raises a warning in this instance. Should this warning be in addition to that warning?

**Comment by thermokarst** [comment]
Good question, @BenKaehler. I'm actually not seeing a warning along those lines. Steps to reproduce:

```sh
$ pip install scikit-learn==0.17
$ wget https://data.qiime2.org/2.0.6/common/gg-13-8-99-515-806-nb-classifier.qza
$ wget https://docs.qiime2.org/2.0.6/data/tutorials/moving-pictures/rep-seqs.qza
$ qiime feature-classifier classify \
  --i-classifier gg-13-8-99-515-806-nb-classifier.qza \
  --i-reads rep-seqs.qza \
  --o-classification taxonomy
```

Output:

```sh
Traceback (most recent call last):
  File "/Users/matthew/miniconda3/envs/q2dev/bin/qiime", line 11, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/matthew/caporaso/qiime2/q2cli/q2cli/commands.py", line 215, in __call__
    results = action(**arguments)
  File "<decorator-gen-201>", line 2, in classify
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/sdk/action.py", line 168, in callable_wrapper
    recorder)
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/sdk/result.py", line 234, in _view
    result = transformation(self._archiver.data_dir)
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/core/transform.py", line 59, in transformation
    new_view = transformer(view)
  File "/Users/matthew/caporaso/qiime2/q2-feature-classifier/q2_feature_classifier/_taxonomic_classifier.py", line 61, in _1
    pipeline = joblib.load(os.path.join(dirname, 'sklearn_pipeline.pkl'))
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 462, in load
    obj = unpickler.load()
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/pickle.py", line 1334, in load_global
    klass = self.find_class(module, name)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/pickle.py", line 1388, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'sklearn.externals.joblib.numpy_pickle' has no attribute 'NumpyArrayWrapper'
```

The greengenes [DB]( https://data.qiime2.org/2.0.6/common/gg-13-8-99-515-806-nb-classifier.qza) was trained with `scikit-learn==0.18.1`, right? When I rerun with that version of scikit-learn, all is good. Seems like this kind of situation will crop up often --- where your environment has a different version of scikit-learn hanging around vs the artifacts you intend to use, and the error that scikit-learn raised above is probably not going to point people in the right direction, unfortunately. I think encoding that version of scikit-learn that was used to produce the classifier, and then comparing the version to the installed version at runtime would help alleviate this problem. Thoughts? Also, @ebolyen and I discussed using the version of scikit-learn saved in the provenance, but we agreed that since the version is intrinsic to the data format, it should probably just be saved somewhere in the artifact's `data/` dir.

**Comment by BenKaehler** [comment]
Thanks @thermokarst. A few things:

- I haven't seen it crash out like that before, just complain.
- You won't see the warning without setting `--verbose`.
- Which version of the classifier are you using? 2.0.6 classifier Artifacts won't work with the 2.0.7 plugin.

It probably is worth adding another warning. I will investigate the best way to do it.

**Comment by thermokarst** [comment]
Thanks @BenKaehler: you don't have to implement this, I think I have a clear idea of what we need to do (but you are more than welcome to!).

> Which version of the classifier are you using? 2.0.6 classifier Artifacts won't work with the 2.0.7 plugin.

That is essentially the point of this issue --- we want to make it more clear to end users when they attempt to use classifiers across versions. By storing the scikit-learn version, we can do a quick compare and bomb out early and let folks know what is wrong and why.

> You won't see the warning without setting --verbose.

I think this new error should be shown without --verbose activated. Basically users would be using the wrong version of an artifact --- we want to make sure they know that.

**Comment by ebolyen** [comment]
I'll work on fixing this. We'll create a new directory format which will track the scikit-learn version out-of-band in another file. Relevant transformers will then raise an exception in needed.

**Comment by jairideout** [comment]
Fixed in #47 AFAIK
